version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ./../:/var/www/html
    networks:
      laravel:

  nginx:
    container_name: nginx
    ports:
      - "127.0.0.22:80:80"
    build:
      context: .
      dockerfile: nginx/Dockerfile
    volumes:
      - ./../:/var/www/html
    depends_on:
      - app
    networks:
      laravel:

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "127.0.0.22:6379:6379"
    networks:
      laravel:

  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    environment:
      MEILI_NO_ANALYTICS: 'true'
      MEILI_MASTER_KEY: 'masterKey'
    ports:
      - "127.0.0.22:7700:7700"
    networks:
      laravel:

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "127.0.0.22:3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      laravel:

networks:
  laravel:
    driver: bridge


volumes:
  db_data:
